// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
	"time"
)

type Banner struct {
	ID        int32          `json:"id"`
	Title     string         `json:"title"`
	ImageUrl  string         `json:"image_url"`
	TargetUrl sql.NullString `json:"target_url"`
	IsActive  bool           `json:"is_active"`
	Position  string         `json:"position"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}
