// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	CreateBanner(ctx context.Context, arg CreateBannerParams) (Banner, error)
	DeleteBanner(ctx context.Context, id int32) error
	GetBanner(ctx context.Context, id int32) (Banner, error)
	ListActiveBanners(ctx context.Context) ([]Banner, error)
	ListBanners(ctx context.Context) ([]Banner, error)
	UpdateBanner(ctx context.Context, arg UpdateBannerParams) (Banner, error)
}

var _ Querier = (*Queries)(nil)
