coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        informational: true
    patch:
      default:
        target: auto
        threshold: 0%
        informational: true

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false