server:
  port: 3000
  host: "0.0.0.0"

database:
  host: "localhost"
  port: 5432
  user: "user"
  password: "pass"
  dbname: "yadwy_db"
  sslmode: "disable"

jwt:
  key: "yJ6IHNlY3JldCBrZXkgZm9yIHRlc3RpbmcgcHVycG9zZXMgb25seSI"